### ISSUE TITLE
spindle-build not handling --prefix=path properly for path strings that contain macros which get expanded by CPP

### ISSUE THREAD

**Issue by mcfadden8** [hpc/Spindle#12]
This is discussed some in pull request https://github.com/hpc/Spindle/pull/9.

I discovered yesterday that when I used prefix=/foo/bar/linux-rhel7 for configure, the C preprocessor was expanding that to "/foo/bar/1-rhel7".  This is because "linux" was itself a macro which expanded to "1" in the code when $SRC/src/logging/spindle_logc.c was pre-processed.

**Comment by mplegendre** [comment]
Fixed.
