### ISSUE TITLE
Investigate using mmap to remap global executables to local ones.

### ISSUE THREAD

**Issue by mcfadden8** [hpc/Spindle#16]
This feature is currently available by running with ```--debug=yes```.  It is also leaving the first page of the global file mapped while the remaining pages are mapped to the local file.  During testing, determine if the entire local file can be used.

Also, determine whether core dumping will work as expected with the text and data remapped in this way.

**Comment by gpaulsen** [comment]
Sorry if this is a silly question:

Won't this cause a lot more memory usage for shared libraries, shared across many processes on the same node?  What's the advantage?

**Comment by mcfadden8** [comment]
@mplegendre and I discovered that we were able to mmap over the entire text and data segment and ```/proc/<pid>/exe``` was preserved.  I need to test this again on a TOSS-2 system to see if this is something that may have been fixed with later versions of Linux.  Just adding a note here so that I don't forget.
