### ISSUE TITLE
Update repo topics

### ISSUE THREAD

**Issue by hauten** [hpc/Spindle#29]
A new page on the LLNL software portal (https://software.llnl.gov/radiuss/) will soon dynamically pull in RADIUSS repos. To achieve this, we need RADIUSS-related repos outside the LLNL org to be tagged with relevant topics. See LLNL/llnl.github.io#17, LLNL/llnl.github.io#151, & https://github.com/LLNL/llnl.github.io/blob/new-home-page/radiuss/README.md for additional context.

For Spindle, please add `performance` and `radiuss`.

Also, you may want to update the computation.llnl.gov in README to https://computation.llnl.gov/projects/spindle/.

**Comment by IanLee1521** [comment]
Done.
