### ISSUE TITLE
master doesn't build

### ISSUE THREAD

**Issue by dsolt** [hpc/Spindle#3]
./configure --enable-sec-none --with-hostbin=/scratch/pmpi/dsolt/WORKSPACE/spindle/myscript.sh

make

make[4]: Entering directory `/scratch/pmpi/dsolt/WORKSPACE/spindle/Spindle/src/client/beboot'
  CC       spindle_bootstrap-spindle_bootstrap.o
  CC       spindle_bootstrap-parseloc.o
  CC       spindle_bootstrap-spindle_mkdir.o
make[4]: *** No rule to make target `../auditclient/exec_util.c', needed by `spindle_bootstrap-exec_util.o'.  Stop.
make[4]: Leaving directory `/scratch/pmpi/dsolt/WORKSPACE/spindle/Spindle/src/client/beboot'

**Comment by mplegendre** [comment]
I'm not reproducing this.  Is this is with 0.10?

If so, the auditclient/exec_util.c source file moved to client/exec_util.c in 0.10.  Based on a quick grep, I don't see any Makefiles or source still referencing the old location.  I wonder if there's a temporary Makefile or depends file that didn't get properly rebuilt after updating to 0.10, and is still referencing the old location.  Does a 'make distclean' and then 'make' fix the issue?

**Comment by dsolt** [comment]
make distclean, <configure again>, make fixed it.   I get a new issue:

make[2]: Entering directory `/scratch/pmpi/dsolt/WORKSPACE/spindle/Spindle/testsuite'
  CCLD     libfuncdict.so
/bin/sh: not-found: command not found
make[2]: *** [libfuncdict.so] Error 127
make[2]: Leaving directory `/scratch/pmpi/dsolt/WORKSPACE/spindle/Spindle/testsuite'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/scratch/pmpi/dsolt/WORKSPACE/spindle/Spindle'
make: *** [all] Error 2

But I think the exec_util.c issue was because of checking out 0.9 and then checking out master and attempting to configure/build from there.

**Comment by dsolt** [comment]
And that was easily fixed by setting MPI_CC and MPI_CXX in a Makefile in testsuite
