### ISSUE TITLE
Manual and spack installation testsuite problems looking for libfunctdict.so

### ISSUE THREAD

**Issue by alansill** [hpc/Spindle#39]
CentOS 7.6 on Intel Westmere

After building and installing LaunchMON and then trying to build Spindle from the current sources via git clone from their current GitHub source locations, I encounter the following problem in the "make" step. It appears to be having trouble finding and using libfuncdict.so in the testsuite area:

```
Making all in testsuite
make[2]: Entering directory `/root/spindle-test/Spindle/testsuite'
  CCLD     libfuncdict.so
/bin/sh: not-found: command not found
make[2]: *** [libfuncdict.so] Error 127
make[2]: Leaving directory `/root/spindle-test/Spindle/testsuite'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/spindle-test/Spindle'
make: *** [all] Error 2
```

Separately installing via spack, it seems to hang during the build and if I look for recently modified files, I see the following:

```
# find /tmp/root/spack-stage/spack-stage-spindle-0.8.1-udgnp63afjbx3uj5nz2k5qo7237kx442/ -mmin -10
/tmp/root/spack-stage/spack-stage-spindle-0.8.1-udgnp63afjbx3uj5nz2k5qo7237kx442/spack-src/testsuite
/tmp/root/spack-stage/spack-stage-spindle-0.8.1-udgnp63afjbx3uj5nz2k5qo7237kx442/spack-src/testsuite/libtest4000.so
```

Checking the shared library that is open, it appears also to lack libfunctdict.so:

```
# ldd /tmp/root/spack-stage/spack-stage-spindle-0.8.1-udgnp63afjbx3uj5nz2k5qo7237kx442/spack-src/testsuite/libtest4000.so
	linux-vdso.so.1 =>  (0x00007ffd0472d000)
	libfuncdict.so => not found
	libc.so.6 => /lib64/libc.so.6 (0x00007f993a6e5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f993afb3000)
```

**Comment by mplegendre** [comment]
This is the same as issue #41 -- libfuncdict.so is supposed to be built with an MPI compiler and it's lack is causing problems. Disabling the testsuite or adding making an MPI compiler present at configure time would help.  

Will close this one as a duplicate.
