### ISSUE TITLE
not-found: command not found

### ISSUE THREAD

**Issue by vsoch** [hpc/Spindle#42]
I'm trying to install spindle and the make is failing with:

```bash
/bin/sh: not-found: command not found
make[2]: *** [libfuncdict.so] Error 127
make[2]: Leaving directory `/spindle/testsuite'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/spindle'
make: *** [all] Error 2
```

Is this something provided by an mpi library? I hadn't installed one in the container yet (is this required for spindle, or does it help with other kinds of loads outside of MPI?)

**Comment by mplegendre** [comment]
Yes, this is the error if no MPI is installed.  I have an open issue to better detect that and error message at configure time.

MPI is only needed to build the testsuite.  So you can also work around this by disabling the testsuite at autoconf time.
